### ISSUE TITLE
How to load / create project config?

### ISSUE THREAD

**Issue by miltoncandelero** [bitcake/bittools-for-blender#1]
The universal config asks for a json and a project but it refuses to create the json or understand an unreal engine project.

maybe I am not understanding the tooltips?

https://user-images.githubusercontent.com/15253010/179020078-0e39608f-ce7b-4934-959f-6c6abca6705f.mp4

**Comment by elamhut** [comment]
<img width="294" alt="blender_Bp6fVrz7Qb" src="https://user-images.githubusercontent.com/36922414/179074148-35bdaaf2-71c9-478e-8558-1f919fe899b1.png">

Something's odd, your menu should be looking like this instead of just being empty, it also shouldn't have a "-" icon if there's no registered projects in existence. Maybe something went wrong when installing the addon?

The way we ask our collaborators to install BitTools is to do a Clone of this entire project directly inside:
C:\Users\yournamehere\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BitTools

This way whenever there's a new version you just do a Pull on your git client and the plugin gets updated. Try doing a fresh install like this, see if it solves your issue.

**Comment by miltoncandelero** [comment]
I downloaded the repo as zip and used blender to install the zip file.

I will try your method and report back 👍

**Comment by elamhut** [comment]
Is it fixed?

**Comment by miltoncandelero** [comment]
Sorry, yes. cloning directly into the blender plugins directory and naming the folder `BitTools` worked!

Thanks a lot <3
